### ISSUE TITLE
onxxruntime _create_inference_session: ValueError

### ISSUE THREAD

**Issue by klaasdewaele** [PeptoneLtd/ADOPT#41]
Thanks for creating this software.

After an apparently succesful install, I run into an error with the example code provided in the README file:

```Traceback (most recent call last):
  File "/home/adopt_test.py", line 19, in <module>
    predicted_z_scores = z_score_pred.get_z_score(representation)
  File "/home/kdewaele/adopt/lib/python3.9/site-packages/adopt-0.4.2.dev0-py3.9.egg/adopt/inference.py", line 79, in get_z_score
  File "/home/kdewaele/adopt/lib/python3.9/site-packages/adopt-0.4.2.dev0-py3.9.egg/adopt/utils.py", line 94, in get_onnx_model_preds
  File "/home/kdewaele/adopt/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/home/kdewaele/adopt/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/kdewaele/adopt/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...) 
```

Could this have to do with microsoft/onnxruntime#17631? Is there a workaround for ADOPT?

**Comment by klaasdewaele** [comment]
Downgrading to onnxruntime 1.15 resolved the issue.
